### ISSUE TITLE
Query regarding usage of GDB command line option

### ISSUE THREAD

**Issue by AmeyaVSingh** [westerndigitalcorporation/swerv-ISS#1]
Hello,

I have a query regarding the command line option: `--gdb`.
How do I use the option to enable remote GDB session?

Currently I have observed the GDB output on stdout.
I have written a script which redirect the `whisper` simulator `stdout` and `stdin` through `netcat`.

But it is an inelegant solution since, I lose any `stdout` prints from riscv binaries linked with newlib.

Thank you for the assistance.
-Ameya Vikram Singh

**Comment by jrahmeh** [comment]
Hi Ameya,

I apologize for not documenting how to use the --gdb option.  I will do so
later today.  Meanwhile, here's a quick howto:
1. You need to use gdb from the riscv toolchain.
2.  If your target riscv program is xyz, then you would issue the command:
gdb  xyz
3. Then you would issue the gdb command:  target remote |  whisper --gdb xyz

Joe

**Comment by jrahmeh** [comment]
Documented --gdb
