### ISSUE TITLE
Compilation Failure due to optimizations on various compilers

### ISSUE THREAD

**Issue by AmeyaVS** [westerndigitalcorporation/swerv-ISS#14]
Due to introduction of template method in Core/HartConfig class in this commit: https://github.com/westerndigitalcorporation/swerv-ISS/commit/882de25a8be2f7944f22205671c6d4a2239bc75d#diff-fdf14d2fb8fede41af40647977544f4eR633

Compilation fails with undefined references of following methods:
```
bool WdRiscv::HartConfig::applyConfig<unsigned int>(WdRiscv::Hart<unsigned int>&, bool) const
bool WdRiscv::HartConfig::finalizeCsrConfig<unsigned int>(std::vector<WdRiscv::Hart<unsigned int>*, std::allocator<WdRiscv::Hart<unsigned int>*> >&) const
bool WdRiscv::HartConfig::applyMemoryConfig<unsigned int>(WdRiscv::Hart<unsigned int>&, bool) const
bool WdRiscv::HartConfig::applyConfig<unsigned long>(WdRiscv::Hart<unsigned long>&, bool) const
bool WdRiscv::HartConfig::finalizeCsrConfig<unsigned long>(std::vector<WdRiscv::Hart<unsigned long>*, std::allocator<WdRiscv::Hart<unsigned long>*> >&) const
bool WdRiscv::HartConfig::applyMemoryConfig<unsigned long>(WdRiscv::Hart<unsigned long>&, bool) const
```

The private static method in HartConfig class does not help alleviate this issue.
As compiler with varying optimization flag inline/removes the API's from the `HartConfig.cpp.o` object file.

The pull request #13 Fixes the issue.

**Comment by jrahmeh** [comment]
Ameya,

Sorry about that.  My bad.  I made a release from the wrong working
area.  Please pull and try again. Problem should be fixed.

Joe

**Comment by jrahmeh** [comment]
Compilation issue fixed.
