### ISSUE TITLE
whisper --disass cli argument doesn't work

### ISSUE THREAD

**Issue by BassMunkee** [westerndigitalcorporation/swerv-ISS#17]
Hi there, I wanted a way to disassemble instructions to their symbolic names and as per the Readme, it is possible through the --disass param for whisper. However, it doesn't seem to be there.

Is this something which has been removed or yet to be implemented. If the general functionality is present but not exposed, I can try to implement it and submit a PR. Any pointers which can help me get started is appreciated.

**Comment by jrahmeh** [comment]
It is a bug. We will fix asap.

**Comment by jrahmeh** [comment]
Hi Bassunkee,

If you run whisper with the --abinames switch it should display the symbolic register names.  If that is not the case, please provide an example and we will fix it.

Joe

**Comment by BassMunkee** [comment]
Thanks for the reply, Joe. 

I'm currently not trying to disassemble a program but just trying to get the names of instructions from their hex value using the `disas` param. This seems to work in interactive mode, but not as a direct param to whisper

There are 2 things that needs to be fixed.

1. The param for disassembly should be corrected from `disass` to `disas` in the Readme.
2. The disas command  seems to work in interactive mode as described in the Readme, but this param has not been implemented in the regular mode, i.e., `whipser **--disas** 0x3b` 

I noticed that it is not being captured in the `parseCmdLineArgs()` function. I'm not familiar with `boost::program_options`, so that's the extent of info I could find out so far.

_Edit: Added the command and output message_

```
> ./whisper --disas 0x93 0x33
> Error: Failed to load ELF file 0x93
> Error: Failed to load ELF file 0x33
```

Hope this helps.

Srikanth

**Comment by jrahmeh** [comment]
Hi Srikanth,

We had decided a while ago not to support command line disassembly (the --disas option).  I will remove the help message for that option.

Joe

**Comment by BassMunkee** [comment]
Thanks for the clarification. Is there a technical reason for dropping it or is it a design decision?

**Comment by jrahmeh** [comment]
It complicates the top level code and the same functionality is available
in interactive mode.
