### ISSUE TITLE
Default c++ build flag -mfma causing Illegal Instruction error

### ISSUE THREAD

**Issue by joeski65** [westerndigitalcorporation/swerv-ISS#19]
This flag makes the compiler generate code that takes advantage of the UltraSPARC Fused Multiply-Add Floating-point instructions.

This causes cryptic 'Illegal Instruction' errors on CPU's that don't support this (which has proved to be plentiful). Can this not be made default, please?

Thanks.

**Comment by jrahmeh** [comment]
No problem.  I will remove it.  It seems to work on x86.  On which processor does it not work?

**Comment by jrahmeh** [comment]
Removed -fmfa from GNUmakefile

**Comment by joeski65** [comment]
> No problem. I will remove it. It seems to work on x86. On which processor does it not work?

Thanks! 
The behaviour changes slightly depending on processor, some give illegal instructions when constructing static variables, others give it right at the end after successful execution of a program.
Two examples respectively: 
Intel(R) Xeon(R) CPU E5-2650
Intel(R) Xeon(R) CPU X5670
