### ISSUE TITLE
missing includes

### ISSUE THREAD

**Issue by sylvanez** [westerndigitalcorporation/swerv-ISS#20]
Hart.cpp is missing an 
#include \<atomic\>

FpRegs.hpp is missing
#include \<string\>

which makes it fail to compile on my system
CentOS 7
gcc 10.2.0
boost 1.74.0 c++17

**Comment by jrahmeh** [comment]
Thank you for reporting this.
I added #include <atomic> to Hart.cpp.  File fpRegs.hpp already has #include <string>.

**Comment by jrahmeh** [comment]
This repository is no longer supported.  Please go here for the latest code: https://github.com/chipsalliance/SweRV-ISS
